Add NN MLP Classifier, confusion matrix and balanced acc score
AndreasPB/aa-final-project-stuff pull request #36
Opened 2022-05-26 23:55 UTC by AndreasPB

* New model
* More tools for analysing performance

2022-05-27 00:21 UTC, AndreasPB commented
Im not 100% sure what I did is Youden Index, but idk

2022-05-28 15:30 UTC, Primdahl26 requested changes

2022-05-28 15:30 UTC, Primdahl26 commented on src/2_train/util.py
> +def summary_report(y_test: list, y_test_pred: list, msg: str | None):
Python 3.9 syntax pls

2022-05-28 15:40 UTC, AndreasPB commented on src/2_train/util.py
> +def summary_report(y_test: list, y_test_pred: list, msg: str | None):
Done

2022-05-28 15:57 UTC, Primdahl26 approved these changes
<img src="https://media4.giphy.com/media/WnOQqMdmPuAGts6Bln/giphy.gif"/>

2022-05-28 15:59 UTC, merged

2022-05-28 16:01 UTC, Primdahl26 commented
<img src="https://media0.giphy.com/media/qhoABJOROS9kQ/giphy.gif"/>